from django.conf.urls import url
from . import views

urlpatterns= [

    url('^$', views.index, name='index'),
    url('^login/$', views.login, name='login'),
    url('^forgotpassword/$', views.forgotpassword, name='forgotpassword'),
    url('^registration/$', views.userregistration, name='registration'),
    url('^pgdetails/$', views.pgdetails, name='pgdetails'),
    url('^pgview/$', views.pgview, name='pgview'),
    url('^delete_details/$', views.delete_details, name='delete_details'),
    url('^update_details/$', views.update_details, name='update_details'),
    url('^PG_db/$', views.PG_db, name='PG_db'),
    url('^guestdetails/$', views.guest_details, name='guestdetails'),
    url('^guestview/$', views.guestview, name='guestview'),
    url('^guest_remove/$', views.guest_remove, name='guest_remove'),
    url('^guest_update/$', views.guest_update, name='guest_update'),
    url('^guest_db/$', views.guest_db, name='guest_db'),
    url('^changepassword/$', views.changepassword, name='changepassword'),
    url('^paycard_db/$', views.paycard_db, name='paycard_db'),
    url('^payment_card/$', views.payment_card, name='payment_card'),
    url('^paycard_remove/$', views.paycard_remove, name='paycard_remove'),
    url('^paycardview/$', views.paycardview, name='paycardview'),
    url('^paycardedit/$', views.paycardedit, name='paycardedit'),
    url('^paycard_search/$', views.paycard_search, name='paycard_search'),
    url('^guestsearch/$', views.guestsearch, name='guestsearch'),
    url('^guest_home/$', views.guest_home, name='guest_home'),
    url('^admin_home/$', views.admin_home, name='admin_home'),
    url('^book_pg/$', views.book_pg, name='book_pg'),
    url('^booking_form_next/$', views.booking_form_next, name='booking_form_next'),
    url('^book_status/$', views.book_status, name='book_status'),
    url('^paymentcardguest/$', views.paymentcardguest, name='paymentcardguest'),
    url('^booking_form/$', views.booking_form, name='booking_form'),
    url('^expense/$', views.expense, name='expense'),
    url('^expenseview/$', views.expenseview, name='expenseview'),
    url('^expenseedit/$', views.expenseedit, name='expenseedit'),
    url('^expense_update/$', views.expense_update, name='expense_update'),
    url('^expense_delete/$', views.expense_delete, name='expense_delete'),
    url('^expense_db/$', views.expense_db, name='expense_db'),
    url('^feedback/$', views.feedback, name='feedback'),
    url('^reviews/$', views.reviews, name='reviews'),
    url('^payment/$', views.payment, name='payment'),
    url('^bill_generate/$', views.bill_generate, name='bill_generate'),
    url('^monthly_report/$', views.monthly_report, name='monthly_report'),
    url('^yearly_report/$', views.yearly_report, name='yearly_report'),
]