# Generated by Django 2.1.7 on 2019-02-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Custid', models.CharField(max_length=50)),
                ('Custname', models.CharField(max_length=200)),
                ('custmob', models.CharField(max_length=50)),
                ('custcity', models.CharField(max_length=200)),
            ],
        ),
    ]
