# Generated by Django 2.1.7 on 2019-02-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.CharField(max_length=200)),
                ('custid', models.CharField(max_length=200)),
                ('PGid', models.CharField(max_length=200)),
                ('bookeddate', models.DateField()),
                ('bookedroomdetails', models.CharField(max_length=200)),
                ('amountpaid', models.IntegerField()),
                ('invoicenumber', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PGid', models.CharField(max_length=200)),
                ('custid', models.CharField(max_length=200)),
                ('ratings', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Guestdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('PGid', models.CharField(max_length=200)),
                ('Custid', models.CharField(max_length=200)),
                ('Bookid', models.CharField(max_length=200)),
                ('StudentPhoto', models.ImageField(upload_to='')),
                ('Studentname', models.CharField(max_length=200)),
                ('Mobilenumber', models.IntegerField()),
                ('Permanentaddress', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Roomno', models.CharField(max_length=200)),
                ('studenttype', models.CharField(max_length=200)),
                ('Depositamount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custid', models.CharField(max_length=200)),
                ('bookid', models.CharField(max_length=200)),
                ('paymode', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PGdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgid', models.CharField(max_length=50)),
                ('pgname', models.CharField(max_length=200)),
                ('pgadress', models.CharField(max_length=200)),
                ('pglocation', models.CharField(max_length=200)),
                ('pgrules', models.CharField(max_length=600)),
                ('pgdescription', models.CharField(max_length=1000)),
                ('contactdetails', models.CharField(max_length=200)),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('image3', models.ImageField(upload_to='')),
                ('image4', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='login',
            old_name='Custid',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='login',
            name='Contactnumber',
        ),
        migrations.RemoveField(
            model_name='login',
            name='Custname',
        ),
    ]
