# Generated by Django 2.1.7 on 2019-02-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0004_auto_20190221_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pgdetails',
            old_name='pgadress',
            new_name='pgaddress',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='ConfirmPassword',
            new_name='Confirmpass',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='NewPassword',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Emailid',
            new_name='emailid',
        ),
    ]
