# Generated by Django 2.1.7 on 2019-03-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0005_auto_20190226_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RenameField(
            model_name='bookingdetails',
            old_name='PGid',
            new_name='advancepayment',
        ),
        migrations.RenameField(
            model_name='bookingdetails',
            old_name='bookedroomdetails',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='bookingdetails',
            old_name='bookid',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='bookingdetails',
            old_name='custid',
            new_name='guestid',
        ),
        migrations.RenameField(
            model_name='bookingdetails',
            old_name='invoicenumber',
            new_name='pgid',
        ),
        migrations.RemoveField(
            model_name='bookingdetails',
            name='amountpaid',
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='roomno',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='roomtype',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='bookeddate',
            field=models.CharField(max_length=100),
        ),
    ]
