# Generated by Django 2.1.7 on 2019-03-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0006_auto_20190301_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestdetails',
            name='StudentPhoto',
        ),
        migrations.AddField(
            model_name='guestdetails',
            name='State',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guestdetails',
            name='studentPhoto',
            field=models.FileField(default='', upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pgdetails',
            name='image1',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='pgdetails',
            name='image2',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='pgdetails',
            name='image3',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='pgdetails',
            name='image4',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
