# Generated by Django 2.1.7 on 2019-03-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0008_auto_20190310_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='paycard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Custid', models.CharField(max_length=200)),
                ('Month', models.IntegerField()),
                ('Date', models.DateField()),
                ('Recivedamount', models.IntegerField()),
                ('Balanceamount', models.IntegerField()),
            ],
        ),
    ]
