# Generated by Django 2.1.7 on 2019-03-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0009_paycard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycard',
            name='Balanceamount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paycard',
            name='Custid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paycard',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paycard',
            name='Month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paycard',
            name='Recivedamount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
