# Generated by Django 2.1.7 on 2019-03-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0011_auto_20190314_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgdetails',
            name='categories',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
