# Generated by Django 2.1.7 on 2019-03-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0012_pgdetails_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(max_length=100)),
                ('expense_name', models.CharField(max_length=100)),
                ('month_of_exp', models.CharField(max_length=100)),
                ('edate', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
