# Generated by Django 2.1.7 on 2019-03-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0013_addexpense'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddExpense',
            new_name='expense',
        ),
    ]
