# Generated by Django 2.1.7 on 2019-03-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0015_auto_20190321_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgdetails',
            name='room_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
