# Generated by Django 2.1.2 on 2019-03-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0017_auto_20190323_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='book_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
