# Generated by Django 2.1.2 on 2019-03-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0019_auto_20190324_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='custfeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PGid', models.CharField(blank=True, max_length=200, null=True)),
                ('custid', models.CharField(blank=True, max_length=200, null=True)),
                ('ratings', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
