# Generated by Django 2.1.2 on 2019-03-24 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0020_auto_20190325_0346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payment',
            new_name='custpayment',
        ),
    ]
