# Generated by Django 2.1.2 on 2019-03-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0021_auto_20190325_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgdetails',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='pgdetails',
            name='image4',
        ),
    ]
