# Generated by Django 2.1.2 on 2019-03-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0022_auto_20190325_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgdetails',
            name='pgdescription',
        ),
        migrations.RemoveField(
            model_name='pgdetails',
            name='pgrules',
        ),
    ]
