# Generated by Django 2.1.2 on 2019-03-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0023_auto_20190325_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgdetails',
            name='occupants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
