# Generated by Django 2.1.7 on 2019-03-27 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0024_pgdetails_occupants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestdetails',
            name='studentPhoto',
        ),
    ]
