# Generated by Django 2.1.7 on 2019-03-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0025_remove_guestdetails_studentphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='amonth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='ayear',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
