# Generated by Django 2.1.7 on 2019-04-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0026_auto_20190329_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensee',
            name='ayear',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
