# Generated by Django 2.1.7 on 2019-04-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0027_expensee_ayear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensee',
            name='edate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
