# Generated by Django 2.1.7 on 2019-04-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0029_auto_20190404_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycard',
            name='Custid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
