# Generated by Django 2.1.7 on 2019-04-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0031_paycard_ayear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestdetails',
            name='Mobilenumber',
            field=models.CharField(max_length=11),
        ),
    ]
