# Generated by Django 2.1.7 on 2019-04-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0033_pgdetails_avilable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgdetails',
            name='avilable',
            field=models.CharField(default='True', max_length=5),
        ),
    ]
