# Generated by Django 2.1.7 on 2019-04-08 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0034_auto_20190409_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgdetails',
            name='avilable',
        ),
    ]
