# Generated by Django 2.1.7 on 2019-04-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0035_remove_pgdetails_avilable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestdetails',
            name='Custid',
            field=models.IntegerField(),
        ),
    ]
