# Generated by Django 2.1.7 on 2019-04-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0036_auto_20190410_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestdetails',
            name='Custid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
