# Generated by Django 2.1.7 on 2019-04-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0040_auto_20190410_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestdetails',
            name='Bookid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guestdetails',
            name='City',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guestdetails',
            name='Depositamount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guestdetails',
            name='Mobilenumber',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='guestdetails',
            name='PGid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guestdetails',
            name='Permanentaddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guestdetails',
            name='Roomno',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guestdetails',
            name='State',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guestdetails',
            name='Studentname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guestdetails',
            name='studenttype',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
